version: '3.8'
services:
  secret-db:
    image: postgres:15.5-alpine
    platform: linux/x86_64
    container_name: secret-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: 1290
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  default:
    name: secretnet
    external: true